export const colors = {
  light: {
    background: '#FFFFFF',
    surface: '#F7F7F8',
    surfaceElevated: '#EFEFEF',
    text: '#1A1A1A',
    textSecondary: '#6B6B6B',
    textTertiary: '#999999',
    primary: '#6C63FF',
    primaryLight: '#E8E6FF',
    userBubble: '#6C63FF',
    userBubbleText: '#FFFFFF',
    assistantBubble: '#F0F0F0',
    assistantBubbleText: '#1A1A1A',
    border: '#E5E5E5',
    error: '#EF4444',
    errorLight: '#FEF2F2',
    success: '#22C55E',
    successLight: '#F0FDF4',
    warning: '#F59E0B',
    warningLight: '#FFFBEB',
    inputBackground: '#F0F0F0',
    statusBar: '#FFFFFF',
    overlay: 'rgba(0, 0, 0, 0.4)',
  },
  dark: {
    background: '#0D0D0D',
    surface: '#1A1A1A',
    surfaceElevated: '#262626',
    text: '#F5F5F5',
    textSecondary: '#A0A0A0',
    textTertiary: '#666666',
    primary: '#7C73FF',
    primaryLight: '#1E1B4B',
    userBubble: '#6C63FF',
    userBubbleText: '#FFFFFF',
    assistantBubble: '#1E1E1E',
    assistantBubbleText: '#F5F5F5',
    border: '#2A2A2A',
    error: '#F87171',
    errorLight: '#450A0A',
    success: '#4ADE80',
    successLight: '#052E16',
    warning: '#FBBF24',
    warningLight: '#451A03',
    inputBackground: '#1E1E1E',
    statusBar: '#0D0D0D',
    overlay: 'rgba(0, 0, 0, 0.6)',
  },
};

export type ColorScheme = typeof colors.light;
